# Generated by Django 4.2.1 on 2023-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50, verbose_name='書名')),
                ('ISBN', models.CharField(max_length=15, verbose_name='ISBN')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('genre', models.CharField(max_length=10, verbose_name='類別')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='books/')),
            ],
        ),
    ]
