# Generated by Django 4.2.1 on 2023-06-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='borrowing_quantity',
            field=models.IntegerField(default=0, verbose_name='預約數量'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=10, verbose_name='性別'),
        ),
    ]
