# Generated by Django 4.2.1 on 2023-06-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_reservedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', '可預約'), ('unavailable', '不可預約')], default='available', max_length=20, verbose_name='狀態'),
        ),
    ]
